# Basic
title: Leopard
subtitle: 夜幕降临
welcome_message: 做一个自由的人
# description: Just A Programmer
creator: <a href="https://github.com/CliffLeopard/">@CliffLeopard</a>

url: "https://cliffleopard.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 工作, description: 正在开发中的应用, url: '/works/'}
    - {title: TAG, description: 标签, url: '/tags/'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: CliffLeopard
    # duoshuo:
# Social
social:
    github: CliffLeopard
    mail: precipiceleopard@gmail.com

# Google Analytics
# ga:
#     id: UA-25719337-1
#     host: onevcat.com
